### ISSUE TITLE
TODO list foe Zowe docker Images

### ISSUE THREAD

**Issue by VitekVlcek-Broadcom** [zowe/zowe-dockerfiles#5]
# Zowe Docker Images
Possible improvements of Zowe Docker Images.

## TODO

- [x] expose folder with certificate `--mount type=bind,source=...,target=/root/zowe/current/components/api-mediation/keystore`
  
- [x] expose static api def of API ML (whole zowe-user-dir) `--mount type=bind,source=...,target=/root/zowe-user-dir`

- [x] support for `--only-install`, `--only-config`, `--post-start` to pause the installation/configuration process
    ```sh
        docker build -t zowe/docker:1.7.1 -t zowe/docker:latest -t  vvvlc/zowe:1.7.1 -t vvvlc/zowe:latest .
        docker run -it \
            -p 8544:8544 \
            -p 7552:7552 \
            -p 7553:7553 \
            -p 7554:7554 \
            -p 8545:8545 \
            -p 8547:8547 \
            -p 1443:1443 \
            --net="bridge" \
            -h myhost.acme.net \
            --env ZOWE_ZOSMF_HOST=mf.acme.net \
            --env ZOWE_ZOSMF_PORT=1443 \
            --env ZOWE_ZSS_HOST=mf.acme.net \
            --env ZOWE_ZSS_PORT=8542 \
            --env LAUNCH_COMPONENT_GROUPS=GATEWAY,DESKTOP \
            --mount type=bind,source=c:/zowe/certs,target=/root/zowe/certs \
            --mount type=bind,source=c:/zowe/keystore,target=/root/zowe/current/components/api-mediation/keystore \
            --mount type=bind,source=c:/zowe/zowe-user-dir,target=/root/zowe-user-dir/ \
            --name "zowe" \
            --rm \
            vvvlc/zowe:latest --only-config
    ```  
    Use `--only-install`, `--only-config`, `--post-start` to stop install/config, then use `mc` to investigate content of image

- [x] do not regenerate certificates every startup, when `/root/zowe/current/components/api-mediation/keystore` already contain certificates
- [x] a start option to enforce regeneration of certificates during startup `--regenerate-certificates` regardless of content of  `/root/zowe/current/components/api-mediation/keystore`
 - [ ] support for Docker on Z
 - [ ] use Alpine instead of Ubuntu  (to shrink footprint of docker image)  (NOTE: Alpine is missing `pax` command)
 - [x] start z/OSMF API emulator to run off Z, (when `ZOWE_ZOSMF_HOST=''` fakeOSMF is started in Docker container), so user can play with MVS, USS, Dataset explorers
    - [ ] improve emulated APIs (Datasets, Jobs, USS files) in fakeOSMF
 - [ ] use dummy Authenticator for ZAF when (`ZOWE_ZSS_HOST/ZOWE_ZSS_PORT` is not specified), so user can login and inspect ZAF without having ZSS running
 - [ ] create zowe account on docker hub and use it instead of [vvvlc/zowe](https://hub.docker.com/r/vvvlc/zowe) account, 
   - [ ] build of docker image as part of Zowe build pipeline see https://github.com/zowe/zowe-dockerfiles/issues/3
   - [ ] improve build process of Zowe docker images so anytime a new Zowe version is published on Zowe.org the zowe project on docker hub does not need to be updated)
